version: '3.9'

services:

  db:
    image: postgres:16-alpine
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
